config/routes.rb
Rails.application.routes.draw do
  root "lockers#index"

  get "/signin", to: "sessions#new"
  get "/signout", to: "sessions#destroy"
  delete "/signout", to: "sessions#destroy"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"

  get "/reset_password", to: "reset_password#new"
  post "/reset_password", to: "reset_password#create"

  resources :users, only: [:edit, :update] do
    collection do
      get "validate_email"
    end
  end

  get "/auth/:provider/callback", to: "authentications#create"
  get "/basecamp/oauth", to: "basecamp/oauth#create"

  resources :sessions, only: [:new, :create, :destroy]
  resources :lockers, except: [:edit], path: "~" do
    resources :addons, only: [:index, :new, :create, :show, :destroy] do
      get :installed, on: :collection
      patch :update_color, on: :member
    end

    namespace :github do
      resources :repos, only: [:index, :create, :update] do
        post "/webhook", action: :webhook, on: :collection
      end
      resources :commits, only: [:index]
      resources :issues, only: [:index, :create]
      resources :pull_requests, only: [:index, :create]
    end

    namespace :todo do
      resources :items
    end

    namespace :google_calendar do
      resources :items, only: [:index]
    end

    namespace :jira do
      resources :items, only: [:index]
    end

    namespace :basecamp do
      resources :oauth, only: [:new]
      resources :todos, only: [:index] do
        post :complete, on: :member
      end
      resources :todolists, only: [:index]
    end

    namespace :bugsnag do
      resources :errors, only: [] do
        collection do
          get :common
          get :recent
        end
      end
    end
  end
end

app/models/addon.rb
# == Schema Information
#
# Table name: addons
#
#  id         :integer          not null, primary key
#  enabled    :boolean          default(FALSE), not null
#  locker_id  :integer          not null
#  api_token  :string
#  name       :string           not null
#  metadata   :jsonb            default({})
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_addons_on_metadata  (metadata)
#

class MetadataValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    if value["domain"]
      unless value["domain"] =~ /https:\/\//
        record.errors[attribute] << "Please use the https protocol for domains"
      end
    end
  end
end

class Addon < ActiveRecord::Base
  belongs_to :locker

  validates :metadata, metadata: true

  scope :enabled, -> { where(enabled: true) }

  def color
    metadata["color"] || "color-1"
  end

  def post_create(*args)
    if name == "jira"
      Jira::Client.new(addon: self).set_session_id(args[0], args[1])
    end
  end
end

app/controllers/addons_controller.rb
class AddonsController < ApplicationController
  layout "addon"

  def index
    @addons = current_locker.addons.enabled.pluck(:name)
  end

  def installed
    @addons = current_locker.addons.enabled
  end

  def new
    @addon = current_locker.addons.new

    render "new-#{params[:addon_name]}"
  end

  def show
  end

  def create
    @addon = current_locker.addons.new(parsed_addon_params)

    if @addon.save
      @addon.post_create(@addon.metadata["username"], @password)

      redirect_to locker_path(current_locker)
    else
      render :new
    end
  end

  def destroy
    @addon = current_locker.addons.find(params[:id])
    @addon.update!(enabled: false)

    redirect_to action: :installed
  end

  def update_color
    @addon = current_locker.addons.find(params[:id])
    @addon.update!(metadata: @addon.metadata.merge(addon_params[:metadata]))

    head :ok
  end

  private

  def addon_params
    params.require(:addon).permit(
      :api_token,
      :name,
      metadata: [
        :username,
        :password,
        :color,
        :domain
      ]
    )
  end

  def parsed_addon_params
    @password = params[:addon].fetch(:metadata, {}).delete(:password)

    addon_params.merge(enabled: true)
  end
end

app/views/addons/index.html.erb
<% content_for :navbar do %>
  <%= render "layouts/locker_navbar" %>
<% end %>

<div class="addon-switcher">
  <nav class="addon-types">
    <div class="addon-type active"><%= link_to "Apps", locker_addons_path(current_locker) %></div>
    <div class="addon-type"><%= link_to "Installed Apps", installed_locker_addons_path(current_locker) %></div>
    <div class="addon-type"><%= link_to "Color Schemes", "#" %></div>
    <div class="addon-type"><%= link_to "Pipes", "#" %></div>
  </nav>
</div>

<div class="addon-store">
  <header class="addon-store-header">
    <h1>Addon Store</h1>
    <p>Power up your locker by connecting to some of these services</p>
  </header>

  <h2>Project Management</h2>
  <% AddonsList.all.each do |addon| %>
    <% unless @addons.include?(addon[:name]) %>
      <article class="addon">
        <%= link_to new_locker_addon_path(current_locker, addon_name: addon[:name]) do %>
          <h3><%= addon[:name].capitalize %></h3>
        <% end %>
        <p class="description"><%= addon[:description] %></p>
      </article>
    <% end %>
  <% end %>
</div>

app/views/addons/installed.html.erb
<% content_for :navbar do %>
  <%= render "layouts/locker_navbar" %>
<% end %>

<div class="addon-switcher">
  <nav class="addon-types">
    <div class="addon-type"><%= link_to "Apps", locker_addons_path(current_locker) %></div>
    <div class="addon-type active"><%= link_to "Installed Apps", installed_locker_addons_path(current_locker) %></div>
    <div class="addon-type"><%= link_to "Color Schemes", "#" %></div>
    <div class="addon-type"><%= link_to "Pipes", "#" %></div>
  </nav>
</div>

<div class="addon-store">
  <header class="addon-store-header">
    <h1>Installed Addons</h1>
    <p>Manage your installed addons</p>
  </header>

  <% @addons.each do |addon| %>
    <article class="addon">
        <h3><%= addon.name.capitalize %></h3>
        <%= button_to "Uninstall", locker_addon_path(current_locker, addon), method: :delete %>
    </article>
  <% end %>
</div>

app/views/addons/new-basecamp.html.erb
<% content_for :navbar do %>
  <%= render "layouts/locker_navbar" %>
<% end %>

<div class="addon-switcher">
  <nav class="addon-types">
    <div class="addon-type active"><%= link_to "Apps", locker_addons_path(current_locker) %></div>
    <div class="addon-type"><%= link_to "Installed Apps", "#" %></div>
    <div class="addon-type"><%= link_to "Color Schemes", "#" %></div>
    <div class="addon-type"><%= link_to "Pipes", "#" %></div>
  </nav>
</div>

<div class="addon-store">
  <header class="addon-store-header">
    <h1>Basecamp</h1>
  </header>

  <h2>Installation Instructions</h2>

  <div class="install-instruction">
    <h3>Authorize DevLocker in Basecamp</h3>
    <p>
      Follow the link to give DevLocker OAuth access to your Trello account so we can populate your Trello widget. Don't worry, you can revoke the access token at any time!
    </p>

    <%= link_to "Integrate with your Basecamp projects", new_locker_basecamp_oauth_path %>
  </div>
</div>

app/views/addons/new-github.html.erb
<% content_for :navbar do %>
  <%= render "layouts/locker_navbar" %>
<% end %>

<div class="addon-switcher">
  <nav class="addon-types">
    <div class="addon-type active"><%= link_to "Apps", locker_addons_path(current_locker) %></div>
    <div class="addon-type"><%= link_to "Installed Apps", "#" %></div>
    <div class="addon-type"><%= link_to "Color Schemes", "#" %></div>
    <div class="addon-type"><%= link_to "Pipes", "#" %></div>
  </nav>
</div>

<div class="addon-store">
  <header class="addon-store-header">
    <h1>Github</h1>
  </header>

  <div class="install-instruction">
    <h3>Authorize DevLocker in Github</h3>
    <p>
      Follow the link below to give DevLocker OAuth access to your Github account. This will let us pull all of your repos, pull requests, branches, etc, so that you can see them all in DevLocker! Don't worry, you can revoke the access token at any time.
    </p>

    <%= link_to "Track your code on Github.", "/auth/github?locker_id=#{current_locker.id}" %>
  </div>
</div>

app/views/addons/new-google.html.erb
<% content_for :navbar do %>
  <%= render "layouts/locker_navbar" %>
<% end %>

<div class="addon-switcher">
  <nav class="addon-types">
    <div class="addon-type active"><%= link_to "Apps", locker_addons_path(current_locker) %></div>
    <div class="addon-type"><%= link_to "Installed Apps", "#" %></div>
    <div class="addon-type"><%= link_to "Color Schemes", "#" %></div>
    <div class="addon-type"><%= link_to "Pipes", "#" %></div>
  </nav>
</div>

<div class="addon-store">
  <header class="addon-store-header">
    <h1>Google Calendar</h1>
  </header>

  <div class="install-instruction">
    <h3>Authorize DevLocker in Google Calendar</h3>
    <p>
      Follow the link below to give DevLocker OAuth access to your Google Calendar. This will let us pull all of your events so that you can see them in DevLocker! Don't worry, you can revoke the access token at any time.
    </p>

    <%= link_to "Sign in with Google", "/auth/google?locker_id=#{current_locker.id}" %>
  </div>
</div>

app/views/addons/new-jira.html.erb
<% content_for :navbar do %>
  <%= render "layouts/locker_navbar" %>
<% end %>

<div class="addon-switcher">
  <nav class="addon-types">
    <div class="addon-type active"><%= link_to "Apps", locker_addons_path(current_locker) %></div>
    <div class="addon-type"><%= link_to "Installed Apps", "#" %></div>
    <div class="addon-type"><%= link_to "Color Schemes", "#" %></div>
    <div class="addon-type"><%= link_to "Pipes", "#" %></div>
  </nav>
</div>

<div class="addon-store">
  <header class="addon-store-header">
    <h1>JIRA</h1>
  </header>

  <h2>Installation Instructions</h2>

  <div class="install-instruction">
    <h3>1. Provide JIRA Domain</h3>
    <p>
    This is the domain at which you log in to JIRA. It probably looks something
    like this: https://my_app.atlassian.net
    * Please note to use the https protocol when providing your JIRA domain
    </p>

    <%= form_for [current_locker, @addon] do |f| %>
      <%= f.hidden_field :name, value: "jira" %>

      <%= f.fields_for :metadata do |metadata_form| %>
        <%= metadata_form.label :domain %>
        <%= metadata_form.text_field :domain, class: "input-form" %>

        <h3>2. Provide JIRA Credentials</h3>
        <p>
        These are the crendentials you use to log in to JIRA. We don't store
        your password in any way (we don't want to be responsible for your crendentials),
        just make an initial request to JIRA for a session ID, which we can hopefully
        use for the rest of time to make requests on your behalf (and we need your username to query for your issues).
        </p>

        <%= metadata_form.label :username %>
        <%= metadata_form.text_field :username, class: "input-form" %>

        <%= metadata_form.label :password %>
        <%= metadata_form.password_field :password, class: "input-form" %>
      <% end %>

      <%= f.submit "Install", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/addons/new-todos.html.erb
<% content_for :navbar do %>
  <%= render "layouts/locker_navbar" %>
<% end %>

<div class="addon-switcher">
  <nav class="addon-types">
    <div class="addon-type active"><%= link_to "Apps", locker_addons_path(current_locker) %></div>
    <div class="addon-type"><%= link_to "Installed Apps", "#" %></div>
    <div class="addon-type"><%= link_to "Color Schemes", "#" %></div>
    <div class="addon-type"><%= link_to "Pipes", "#" %></div>
  </nav>
</div>

<div class="addon-store">
  <header class="addon-store-header">
    <h1>Todo List</h1>
  </header>

  <div class="install-instruction">
    <p>To enable TodoLists simply press the install button below</p>
  </div>

  <%= form_for [current_locker, @addon] do |f| %>
      <%= f.hidden_field :name, value: "todos" %>
      <div class="form-group">
        <%= f.submit "Install", class: "btn" %>
      </div>
  <% end %>
</div>

app/views/addons/new-trello.html.erb
<% content_for :navbar do %>
  <%= render "layouts/locker_navbar" %>
<% end %>

<div class="addon-switcher">
  <nav class="addon-types">
    <div class="addon-type active"><%= link_to "Apps", locker_addons_path(current_locker) %></div>
    <div class="addon-type"><%= link_to "Installed Apps", "#" %></div>
    <div class="addon-type"><%= link_to "Color Schemes", "#" %></div>
    <div class="addon-type"><%= link_to "Pipes", "#" %></div>
  </nav>
</div>

<div class="addon-store">
  <header class="addon-store-header">
    <h1>Trello</h1>
  </header>
  <h2>Installation Instructions</h2>

  <div class="install-instruction">
    <h3>1. Authorize DevLocker in Trello</h3>
    <p>
      Follow the link below to authorize DevLocker to access your Trello account.
      DevLocker will only ask for read-access.
    </p>
    <p>
    <%= link_to "Get Trello API Key",
      "https://trello.com/1/authorize?key=0d8d50b318a5bfdbf80d56ad597112c1&name=DevLocker&expiration=never&response_type=token",
      target: "_blank"
    %>
  </p>
  </div>

  <div class="install-instruction">
    <h3>2. Copy API Key</h3>
    <p>
      Once you have approved authorization, copy the API key and paste it in
      the form below.
    </p>

    <%= form_for [current_locker, @addon] do |f| %>
      <%= f.hidden_field :name, value: "trello" %>
      <div class="form-group">
        <%= f.label 'Api key' %>:
        <%= f.text_field :api_token, class: "input-form" %>
      </div>

      <div class="form-group">
        <%= f.submit "Install", class: "btn" %>
      </div>
    <% end %>
  </div>
</div>