config/routes.rb
Rails.application.routes.draw do
  root "lockers#index"

  get "/signin", to: "sessions#new"
  get "/signout", to: "sessions#destroy"
  delete "/signout", to: "sessions#destroy"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"

  get "/reset_password", to: "reset_password#new"
  post "/reset_password", to: "reset_password#create"

  resources :users, only: [:edit, :update] do
    collection do
      get "validate_email"
    end
  end

  get "/auth/:provider/callback", to: "authentications#create"
  get "/basecamp/oauth", to: "basecamp/oauth#create"

  resources :sessions, only: [:new, :create, :destroy]
  resources :lockers, except: [:edit], path: "~" do
    resources :addons, only: [:index, :new, :create, :show, :destroy] do
      get :installed, on: :collection
      patch :update_color, on: :member
    end

    namespace :github do
      resources :repos, only: [:index, :create, :update] do
        post "/webhook", action: :webhook, on: :collection
      end
      resources :commits, only: [:index]
      resources :issues, only: [:index, :create]
      resources :pull_requests, only: [:index, :create]
    end

    namespace :todo do
      resources :items
    end

    namespace :google_calendar do
      resources :items, only: [:index]
    end

    namespace :jira do
      resources :items, only: [:index]
    end

    namespace :basecamp do
      resources :oauth, only: [:new]
      resources :todos, only: [:index] do
        post :complete, on: :member
      end
      resources :todolists, only: [:index]
    end

    namespace :bugsnag do
      resources :errors, only: [] do
        collection do
          get :common
          get :recent
        end
      end
    end
  end
end

app/models/locker.rb
# == Schema Information
#
# Table name: lockers
#
#  id         :integer          not null, primary key
#  name       :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_lockers_on_user_id  (user_id)
#

class Locker < ActiveRecord::Base
  belongs_to :user

  has_many :addons, dependent: :destroy
  has_many :todo_items, class_name: Todo::Item, dependent: :destroy
end

app/controllers/lockers_controller.rb
class LockersController < ApplicationController
  def index
    @lockers = current_user.lockers
  end

  def new
    @locker = current_user.lockers.new
  end

  def show
    locker = current_user.lockers.find(params[:id])
    @enabled_addons = locker.addons.enabled.map { |addon| addon.name.camelize + "App" }
  end

  def create
    @locker = current_user.lockers.new(locker_params)

    if @locker.save
      redirect_to @locker
    else
      render :new
    end
  end

  def destroy
    @locker = current_user.lockers.find(params[:id])
    @locker.destroy

    redirect_to action: :index
  end

  private

  def locker_params
    params.require(:locker).permit(:name)
  end
end

app/views/lockers/_locker.html.erb
<%= link_to locker do %>
  <h2><%= locker.name %><h2>
<% end %>
<%= link_to "Delete", locker_path(locker), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/lockers/index.html.erb
<% content_for :navbar do %>
  <%= render "layouts/home_navbar" %>
<% end %>

<h1>Lockers</h1>
<%= link_to "Create new Locker", new_locker_path %>

<div class="lockers">
  <%= render @lockers %>
</div>

app/views/lockers/new.html.erb
<% content_for :navbar do %>
  <%= render "layouts/home_navbar" %>
<% end %>

<%= form_for @locker do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input-form" %>
  </div>

  <div class="form-group">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/lockers/show.html.erb
<% content_for :navbar do %>
  <%= render "layouts/locker_navbar" %>
<% end %>

<div id="react"></div>

<script>
  var reactNode = document.getElementById("react");
  var ReactComponent = window.React.createFactory(window.Devlocker.Root);
  window.React.render(
    ReactComponent({
      enabledAddons: <%= raw(@enabled_addons.to_json.html_safe) %>
    }),
    reactNode
  );
</script>