config/routes.rb
Rails.application.routes.draw do
  root "lockers#index"

  get "/signin", to: "sessions#new"
  get "/signout", to: "sessions#destroy"
  delete "/signout", to: "sessions#destroy"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"

  get "/reset_password", to: "reset_password#new"
  post "/reset_password", to: "reset_password#create"

  resources :users, only: [:edit, :update] do
    collection do
      get "validate_email"
    end
  end

  get "/auth/:provider/callback", to: "authentications#create"
  get "/basecamp/oauth", to: "basecamp/oauth#create"

  resources :sessions, only: [:new, :create, :destroy]
  resources :lockers, except: [:edit], path: "~" do
    resources :addons, only: [:index, :new, :create, :show, :destroy] do
      get :installed, on: :collection
      patch :update_color, on: :member
    end

    namespace :github do
      resources :repos, only: [:index, :create, :update] do
        post "/webhook", action: :webhook, on: :collection
      end
      resources :commits, only: [:index]
      resources :issues, only: [:index, :create]
      resources :pull_requests, only: [:index, :create]
    end

    namespace :todo do
      resources :items
    end

    namespace :google_calendar do
      resources :items, only: [:index]
    end

    namespace :jira do
      resources :items, only: [:index]
    end

    namespace :basecamp do
      resources :oauth, only: [:new]
      resources :todos, only: [:index] do
        post :complete, on: :member
      end
      resources :todolists, only: [:index]
    end

    namespace :bugsnag do
      resources :errors, only: [] do
        collection do
          get :common
          get :recent
        end
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <ul>
    <p>DevLocker</p>
    <li><%= link_to "Source Code", "https://github.com/devlocker/devlocker" %></li>
    <li><%= link_to "Install", "#" %></li>
    <li><%= link_to "Mobile", "#" %></li>
    <li><%= link_to "Tour", "#" %></li>
  </ul>
  <ul>
    <p>About Us</p>
    <li><%= link_to "Blog", "http://devlocker.github.io" %></li>
    <li><%= link_to "Team", "http://devlocker.github.io" %></li>
    <li><%= link_to "News", "http://devlocker.github.io" %></li>
    <li><%= link_to "Jobs", "http://devlocker.github.io" %></li>
  </ul>
  <ul>
    <p>Support</p>
    <li><%= link_to "Help", "https://github.com/devlocker/devlocker" %></li>
    <li><%= link_to "Documentation", "https://github.com/devlocker/devlocker" %></li>
    <li><%= link_to "Talk to a Person", "#" %></li>
    <li><%= link_to "Privacy", "#" %></li>
  </ul>
  <ul>
    <p>Community</p>
    <li><%= link_to "Github", "https://github.com/orgs/devlocker/teams/owners" %></li>
    <li><%= link_to "Twitter", "#" %></li>
    <li><%= link_to "Developers", "https://github.com/orgs/devlocker/teams/owners" %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<head>
  <title>DevLocker</title>
  <link href="//fonts.googleapis.com/css?family=Fira+Sans:400,500,700,400italic" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Source+Code+Pro:400,600,700" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_home_navbar.html.erb
<nav class="navbar navbar-brand">
  <div class="branding">
    <%= link_to "DevLocker", lockers_path, class: "important" %>
  </div>
  <div class="arrow-right"></div>

  <div class="right">
    <span class="info"><%= long_time %></span>
    <%= link_to current_user.name, edit_user_path(current_user) %>
    <%= link_to "Signout", signout_path %>
  </div>
</nav>

app/views/layouts/_locker_navbar.html.erb
<nav class="navbar">
  <div class="branding">
    <%= link_to "DevLocker", lockers_path, class: "important" %>
    <span>/</span>
    <%= link_to current_locker.name, locker_path(current_locker), class: "sub" %>
  </div>
  <div class="arrow-right"></div>

  <div class="right">
    <span class="info"><%= long_time %></span>
    <%= link_to "App Store", locker_addons_path(current_locker), class: "app-store" %>
    <%= link_to current_user.name, edit_user_path(current_user) %>
    <%= link_to "Signout", signout_path %>
  </div>
</nav>

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/header" %>
  <body>
    <nav class="navbar">
      <div class="branding">
        <%= link_to "DevLocker", "#", class: "important" %>
        <span>/</span>
        <%= link_to "Sign Up", "#", class: "sub" %>
      </div>
      <div class="arrow-right"></div>

      <div class="right">
      </div>
    </nav>

    <div class="container" id="sign_up"></div>
    <script>
      var signUpNode = document.getElementById("sign_up");
      var SignUpComponent = window.React.createFactory(window.Devlocker.SignUpTerminal.Terminal);
      window.React.render(
        SignUpComponent(),
        signUpNode
      );
    </script>

  </body>
  <%= render "layouts/footer" %>
</html>

app/views/layouts/addon.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/header" %>
  <body>
      <%= yield :navbar %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
  <%= javascript_include_tag "application" %>
  <%= render "layouts/footer" %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/header" %>
  <body>
    <%= yield :navbar %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

    <div class="locker">
      <%= yield %>
    </div>

  </body>
</html>